### ISSUE TITLE
Error running program

### ISSUE THREAD

**Issue by caeken** [Ridog/MidJourney_WebWrapper#1]
An error occurred while running the program, prompting the following message:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from flask_app import start_flask_app, stop_flask_app
  File "/usr/src/app/flask_app.py", line 2, in <module>
    from flask_socketio import SocketIO, send
  File "/usr/local/lib/python3.4/site-packages/flask_socketio/__init__.py", line 21, in <module>
    import socketio
  File "/usr/local/lib/python3.4/site-packages/socketio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python3.4/site-packages/socketio/client.py", line 7, in <module>
    import engineio
  File "/usr/local/lib/python3.4/site-packages/engineio/__init__.py", line 3, in <module>
    from .client import Client
  File "/usr/local/lib/python3.4/site-packages/engineio/client.py", line 2, in <module>
    from json import JSONDecodeError
ImportError: cannot import name 'JSONDecodeError'

I have tried many methods but failed to solve the problem. What is the reason?

**Comment by Ridog** [comment]
Hey sorry! All this code is super early alpha I haven't really prepped it for release. It looks like you are using python 3.4.  I developed this with 3.11 so try updating your python installation and then see if it works.
